Add support for left palette panel option
elyra-ai/pipeline-editor pull request #137
Opened 2021-06-23 22:51 UTC by marthacryan

Fixes elyra-ai/elyra#1795. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2021-06-23 22:54 UTC, bourdakos1 approved these changes
lgtm

2021-06-24 15:40 UTC, marthacryan commented
Found an issue with this PR - going to leave in draft until it's fixed up

2021-06-24 18:28 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineEditor/index.tsx
> +            let defaultTab = leftPalette ? "pipeline-properties" : "palette";
👀 lint

2021-06-24 19:48 UTC, ajbozarth requested changes
Code LGTM, tested it locally and over looks solid, but the side bar UI is wonky when closed, as seen in this screenshot the text is cut off, we should either replace that text with an icon or figure something else out. 
<img width="279" alt="Screen Shot 2021-06-24 at 2 46 41 PM" src="https://user-images.githubusercontent.com/13952758/123323502-32da9e00-d4fb-11eb-8143-e587a8045685.png">

2021-06-24 19:52 UTC, ajbozarth commented
also personally I think as long as we only have one tab on the left for pallete we should have it default to open, at minimum we should have it default to open for an empty pipeline

2021-06-25 15:41 UTC, akchinSTC commented
@lresende - when do we think we can get this in by? early next week? Just need to finalize the look of the UI and flow so that ptitzler can work on taking screens for documentation etc.

2021-06-25 15:47 UTC, lresende commented
Can we get a screenshot of the current status? If the above screenshot is current we need to make it better, maybe by using component icon + tooltip? We should have something very similar to the one on the issue.

2021-06-28 19:45 UTC, ptitzler commented
Feedback based on today's build.

- There appears to be a palette issue (the entires only show up after I randomly click on things).
  
   ![empty](https://user-images.githubusercontent.com/13068832/123692829-219bd500-d80c-11eb-8549-8875b403f426.gif)

- The text should label these as _component[s]_ instead of _node[s]_ due to new terminology we are introducing (see https://github.com/elyra-ai/elyra/pull/1839)  In a nutshell, a [pipeline] node is an  instance of a generic or typed component. This way our terminology is consistent with KF.
![image](https://user-images.githubusercontent.com/13068832/123693098-793a4080-d80c-11eb-9d84-7886da1743b6.png)


![image](https://user-images.githubusercontent.com/13068832/123691353-5c9d0900-d80a-11eb-9230-b268f22fc0d8.png)

- Perhaps use a dark font color? As is there is too little contrast between white and gray. The color choices should probably be revisited for the dark theme (:
- Does the "nodes" text serve a purpose?
- What's the source for the 2 component specific labels for the three generic components? It appears that for other components the second label is the description. If that's the case, the descriptions for the three generic components should probably be "Run <Python script| notebook | R script> 


![image](https://user-images.githubusercontent.com/13068832/123694049-ab986d80-d80d-11eb-92fa-104f35fb5de9.png)

- Is there a way to make the collapsed view more useful to the user? As is one would have to expand the view or hover over each custom component entry to determine which one is which. Going forward the majority of entries in the list will be custom components and the icon the same for all, which gives the current rendering a "buggy" appearance. If there's no good way I'd +1 Alex's suggestion to show the component  list in the palette expanded by default.
- For the time being, could the list be sorted? Right now the order appears to reflect the order in the registry, which is random.

2021-06-28 19:55 UTC, marthacryan commented
@lresende @ptitzler The "Nodes" dropdown is because of the setup of the palette - it requires using categories, so we have just one category called nodes (which was coded to not be shown in the current implementation of the palette as a tab). Unfortunately it doesn't seem to be possible to just give a list of nodes without any categories (or have a category selected by default), but we have a couple options:
* Add more categories so that it looks more natural to have categories
* Reuse the `PalettePanel` - the one part about this would be that it might require a good bit of extra work to have a "Narrow" mode like the built-in palette has. If we don't care about the "narrow" mode or if we can put that off a bit, I think this might be the best solution

2021-06-28 20:24 UTC, ptitzler commented
> Add more categories (with icons?) so that it looks more natural to have categories

Have we tried yet to define what what categories are? The most simplistic approach would distinguish between generic components ("Elyra components that are supported by every runtime) and custom components (the others), but won't help  in the mid- or long-term because the majority of entries would always be in the second category.

> Reuse the PalettePanel class currently used in the right panel - the one part about this would be that it might require a good bit of extra work to have a "Narrow" mode like the built-in palette has. It also doesn't have a search feature yet. If we don't care about the "narrow" mode or if we can put that off a bit, I think this might be the best solution

I feel that "we don't care about the "narrow" mode" -> defer might be the right thing to do initially:
- since the palette is new and users not familiar with the example components, it's likely that users would choose the expanded view because it helps them decide which components to use
- we could use the button to show/hide the palette to avoid using up precious canvas space permanently until a more useful narrow mode is available.
- as is the narrow mode clashes a bit with category labels (which I guess would be text based) because the narrow mode size would have to be at least as wide as the longest category name

2021-06-29 15:07 UTC, marthacryan commented
Updated to take entire `palette` as a prop, rather than `nodes`, which allows the JL extension to define categories / icons for categories as needed.

2021-06-30 20:07 UTC, ptitzler commented
Layout wise this seems a lot better with the latest updates! Search etc looks fine!

- I'm still seeing the font/theme color issues
- Nit: `Palette` tooltip ->  `Minimize Palette/Maximize Palette"  (similar to what we have for the properties panel)
![image](https://user-images.githubusercontent.com/13068832/124022764-1a0e3480-d9a2-11eb-8216-4438fc7e2678.png)
- Could you please add a default description for each generic node (`Run XX`)?
  ![image](https://user-images.githubusercontent.com/13068832/124024254-cef52100-d9a3-11eb-98f2-213aafc9ae4b.png)

2021-06-30 20:11 UTC, ptitzler commented
Might want to update the wording here to help new users get started (look for the palette!)

![image](https://user-images.githubusercontent.com/13068832/124024764-812ce880-d9a4-11eb-9041-e6a782ef21ea.png)

2021-06-30 20:28 UTC, ptitzler commented
I didn't test this with "many" component entries, but assume that the palette will have its own scroll bar?

2021-07-01 15:46 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.test.ts
> +import { createPalette, nodeSpec } from "../test-utils";
haha smart!

2021-07-01 15:54 UTC, bourdakos1 requested changes
looks great! Just a request to add better typings for one of the new functions

2021-07-01 15:54 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.ts
> +  getAllPaletteNodes(): any[] {
we should specify the actual type here

2021-07-01 15:54 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.ts
> +      const properties = info.map((i: any) => {
once we define a real type in `getAllPaletteNodes` we should be able to remove `any` here

2021-07-01 17:39 UTC, marthacryan commented
> I didn't test this with "many" component entries, but assume that the palette will have its own scroll bar?

@ptitzler Just checked and it does

> * I'm still seeing the font/theme color issues
Fixed!
![image](https://user-images.githubusercontent.com/6673460/124160386-d24ee200-da61-11eb-9d42-b75275640c47.png)
![image](https://user-images.githubusercontent.com/6673460/124160485-eb579300-da61-11eb-8bc1-f48289b8b727.png)
![image](https://user-images.githubusercontent.com/6673460/124166210-29f04c00-da68-11eb-8ae8-79e27d01ebee.png)
![image](https://user-images.githubusercontent.com/6673460/124166236-31175a00-da68-11eb-8144-7dc05fba5418.png)

> * Nit: `Palette` tooltip ->  `Minimize Palette/Maximize Palette"  (similar to what we have for the properties panel)
>   ![image](https://user-images.githubusercontent.com/13068832/124022764-1a0e3480-d9a2-11eb-8216-4438fc7e2678.png)
This is actually not configurable, it's built in to the canvas. 

> * Could you please add a default description for each generic node (`Run XX`)?
>   ![image](https://user-images.githubusercontent.com/13068832/124024254-cef52100-d9a3-11eb-98f2-213aafc9ae4b.png)
That'll require backend changes on the Elyra side. @kiersten-stokes Maybe you could add more descriptions to the nodes?

2021-07-01 19:20 UTC, marthacryan commented
@bourdakos1 How does that last commit look for types?

2021-07-01 22:37 UTC, bourdakos1 requested changes

2021-07-01 22:37 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.ts
> +      ([] as any[])
we shouldn't need to cast this as `any[]`

2021-07-01 22:37 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.ts
> +                (p: any) => p.parameter_ref === problem.property
no `any`

2021-07-01 22:37 UTC, bourdakos1 commented on packages/pipeline-editor/src/test-utils.tsx
> +      ...node,
I think this is what was causing your typescript issues. `node` has `type` which would override `type: "execution_node",` above

2021-07-01 22:40 UTC, bourdakos1 commented on packages/pipeline-editor/src/types.ts
> +  app_data?: any;
I think we should remove `CustomNodeSpecification` from here

2021-07-02 16:27 UTC, bourdakos1 commented on packages/pipeline-editor/src/PipelineController/index.ts
> +
I need to take a closer look at this, seems a bit fishy

2021-07-02 16:27 UTC, bourdakos1 commented on packages/pipeline-editor/src/common-canvas.d.ts
> +
need to take a closer look at this too

2021-07-02 19:54 UTC, bourdakos1 approved these changes

2021-07-02 20:56 UTC, bourdakos1 requested changes

2021-07-02 20:56 UTC, bourdakos1 commented on packages/pipeline-editor/src/common-canvas.d.ts
> +        /**
Label and  image should be removed from here

2021-07-02 21:29 UTC, bourdakos1 approved these changes

2021-07-02 21:34 UTC, ajbozarth approved these changes
skimmed the code and checked the UI/UX locally and it looks ok, trusting other for the more through review

2021-07-06 17:24 UTC, merged