Migrate v5 -> v6
elyra-ai/pipeline-editor pull request #172
Opened 2021-11-08 17:10 UTC by ajbozarth

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2021-11-10 20:45 UTC, ptitzler commented
Migration requirements from https://github.com/elyra-ai/elyra/pull/2286:

New pipeline files that utilize example components include the following metadata for `op` and `component_source`:

```
"op": "elyra-kfp-examples-catalog:a08014f9252f",
"component_source": "{'catalog_type': 'elyra-kfp-examples-catalog', 'component_ref': {'component-id': 'download_data.yaml'}}",
```

**op**:
 -  the value of `component_source.catalog_type`
 - colon
 - hash calculated based on the value of `component_source.component_ref.component-id`

**component_source**
 - `catalog_type`: static string `elyra-kfp-examples-catalog` (for all runtime types)
 - `component_ref.component:id`: the _current_ (pre 3.3) component file name without a path (the file names have not changed from the previous version)

2021-11-10 21:17 UTC, ptitzler commented
Metadata that 3.2.2  produces (@kiersten-stokes please chime in - feel free to edit this comment)

local file component:

```
"op": "run_notebook_using_papermill_Runnotebookusingpapermill"
"component_source": "/opt/anaconda3/envs/ga_32/share/jupyter/components/kfp/run_notebook_using_papermill.yaml",
```

URL component:

```
"op": "component_Calculatedatahash",
"component_source": "https://raw.githubusercontent.com/kubeflow/pipelines/1.6.0/components/basics/Calculate_hash/component.yaml",
```

2021-11-10 21:29 UTC, kiersten-stokes commented
All of @ptitzler's comments look right to me. I have the updated mapping of old `ops` and `component_source` fields [here](https://github.com/elyra-ai/elyra/issues/2262#issuecomment-962129351)!

2021-11-11 00:26 UTC, akchinSTC commented
tried with a few pipelines I had from 3.2 but after migration box clicked ok, shows blank canvas. 
example of aa pipeline:
```
{
  "doc_type": "pipeline",
  "version": "3.0",
  "json_schema": "http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json",
  "id": "elyra-auto-generated-pipeline",
  "primary_pipeline": "primary",
  "pipelines": [
    {
      "id": "primary",
      "nodes": [
        {
          "id": "15a3f4ab-9c70-4aa7-9a7b-33b561ad4b7e",
          "type": "execution_node",
          "op": "bash_operator_BashOperator",
          "app_data": {
            "component_parameters": {
              "bash_command": "cat /etc/hosts && echo $TEST_ENV",
              "xcom_push": true,
              "env": "{\"TEST_ENV\": \"Hello World\"}",
              "output_encoding": "utf-8"
            },
            "label": "",
            "component_source": "https://raw.githubusercontent.com/apache/airflow/1.10.15/airflow/operators/bash_operator.py",
            "ui_data": {
              "label": "BashOperator",
              "image": "data:image/svg+xml;utf8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%20175%20270%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Cg%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20d%3D%22M4.18587%20172.44L86.3959%2088.1685C86.9109%2087.6406%2087.0096%2086.8244%2086.5801%2086.2249C81.5792%2079.2442%2072.3564%2078.0343%2068.9375%2073.3445C58.8101%2059.4522%2056.2405%2051.5891%2051.8887%2052.0768C51.5847%2052.1109%2051.3137%2052.2745%2051.1001%2052.4934L21.4015%2082.9367C4.31645%20100.45%201.86636%20139.01%201.41703%20171.298C1.39673%20172.757%203.1669%20173.484%204.18587%20172.44Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%23017CEE%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20d%3D%22M172.44%20170.357L88.1685%2088.1466C87.6406%2087.6316%2086.8244%2087.5328%2086.2249%2087.9623C79.2443%2092.9633%2078.0344%20102.186%2073.3445%20105.605C59.4522%20115.732%2051.5891%20118.302%2052.0768%20122.654C52.1109%20122.958%2052.2745%20123.229%2052.4935%20123.442L82.9367%20153.141C100.45%20170.226%20139.01%20172.676%20171.298%20173.125C172.757%20173.146%20173.484%20171.376%20172.44%20170.357Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%2300AD46%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20fill-rule%3D%22evenodd%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20d%3D%22M82.9363%20153.141C73.3696%20143.809%2068.9312%20125.346%2087.2715%2087.2725C57.4647%20100.593%2047.0194%20118.103%2052.1578%20123.116L82.9363%20153.141Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%2304D659%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20d%3D%22M170.355%202.10462L88.1451%2086.376C87.6301%2086.9039%2087.5314%2087.72%2087.9609%2088.3195C92.9618%2095.3002%20102.185%2096.5101%20105.603%20101.2C115.731%20115.092%20118.301%20122.955%20122.652%20122.468C122.956%20122.434%20123.227%20122.27%20123.441%20122.051L153.139%2091.6077C170.225%2074.0942%20172.675%2035.5346%20173.124%203.24627C173.144%201.78719%20171.374%201.0601%20170.355%202.10462Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%2300C7D4%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20fill-rule%3D%22evenodd%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20d%3D%22M153.14%2091.6077C143.807%20101.174%20125.344%20105.613%2087.2705%2087.2725C100.591%20117.079%20118.101%20127.525%20123.114%20122.386L153.14%2091.6077Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%2311E1EE%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20d%3D%22M2.10315%204.18733L86.3745%2086.3973C86.9024%2086.9123%2087.7185%2087.0111%2088.3181%2086.5816C95.2987%2081.5807%2096.5086%2072.3579%20101.198%2068.939C115.091%2058.8116%20122.954%2056.242%20122.466%2051.8902C122.432%2051.5862%20122.268%2051.3152%20122.05%2051.1016L91.6063%2021.403C74.0928%204.31792%2035.5331%201.86783%203.2448%201.4185C1.78572%201.39819%201.05863%203.16836%202.10315%204.18733Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%23E43921%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20fill-rule%3D%22evenodd%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20d%3D%22M91.6057%2021.4025C101.172%2030.7352%20105.611%2049.1977%2087.2705%2087.2714C117.077%2073.9511%20127.523%2056.4408%20122.384%2051.4281L91.6057%2021.4025Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%23FF7557%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20fill-rule%3D%22evenodd%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20d%3D%22M21.4025%2082.9368C30.7352%2073.3701%2049.1977%2068.9317%2087.2714%2087.272C73.951%2057.4652%2056.4408%2047.0199%2051.4281%2052.1583L21.4025%2082.9368Z%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20fill%3D%22%230CB6FF%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Ccircle%20cx%3D%2287.2838%22%20cy%3D%2287.2606%22%20r%3D%223.67606%22%20transform%3D%22rotate(-0.709386%2087.2838%2087.2606)%22%20fill%3D%22%234A4848%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cpath%20d%3D%22M19.1525%20224.647C18.9422%20224.647%2018.7581%20224.568%2018.6004%20224.41C18.4426%20224.253%2018.3638%20224.069%2018.3638%20223.858C18.3638%20223.648%2018.3769%20223.503%2018.4032%20223.424L28.1835%20197.909C28.3938%20197.331%2028.8145%20197.041%2029.4455%20197.041H32.1271C32.7581%20197.041%2033.1788%20197.331%2033.3891%20197.909L43.13%20223.424L43.2088%20223.858C43.2088%20224.069%2043.13%20224.253%2042.9722%20224.41C42.8145%20224.568%2042.6304%20224.647%2042.4201%20224.647H40.4088C40.1196%20224.647%2039.8962%20224.581%2039.7384%20224.45C39.5807%20224.292%2039.4755%20224.134%2039.4229%20223.977L37.2539%20218.377H24.3187L22.1497%20223.977C22.0971%20224.134%2021.9788%20224.292%2021.7948%20224.45C21.637%20224.581%2021.4267%20224.647%2021.1638%20224.647H19.1525ZM36.1102%20214.985L30.7863%20200.985L25.4624%20214.985H36.1102ZM47.8593%20232.14C47.5964%20232.14%2047.3729%20232.048%2047.1888%20231.864C47.0311%20231.706%2046.9522%20231.496%2046.9522%20231.233V205.047C46.9522%20204.784%2047.0311%20204.574%2047.1888%20204.416C47.3729%20204.232%2047.5964%20204.14%2047.8593%20204.14H49.6734C49.9363%20204.14%2050.1466%20204.232%2050.3043%20204.416C50.4884%20204.574%2050.5804%20204.784%2050.5804%20205.047V206.782C52.0527%20204.758%2054.2086%20203.746%2057.048%20203.746C59.8086%20203.746%2061.8724%20204.613%2063.2396%20206.348C64.633%20208.084%2065.3823%20210.318%2065.4874%20213.053C65.5137%20213.342%2065.5269%20213.789%2065.5269%20214.393C65.5269%20214.998%2065.5137%20215.445%2065.4874%20215.734C65.3823%20218.442%2064.633%20220.677%2063.2396%20222.439C61.8461%20224.174%2059.7823%20225.041%2057.048%20225.041C54.3137%20225.041%2052.1842%20224.055%2050.6593%20222.084V231.233C50.6593%20231.496%2050.5804%20231.706%2050.4227%20231.864C50.2649%20232.048%2050.0546%20232.14%2049.7917%20232.14H47.8593ZM56.2198%20221.847C58.0865%20221.847%2059.4405%20221.269%2060.2818%20220.112C61.1494%20218.955%2061.6227%20217.43%2061.7015%20215.537C61.7278%20215.274%2061.741%20214.893%2061.741%20214.393C61.741%20209.424%2059.9006%20206.94%2056.2198%20206.94C54.4058%20206.94%2053.0386%20207.545%2052.1184%20208.754C51.2245%20209.937%2050.7381%20211.357%2050.6593%20213.013L50.6198%20214.512L50.6593%20216.05C50.7119%20217.601%2051.2114%20218.955%2052.1579%20220.112C53.1043%20221.269%2054.4583%20221.847%2056.2198%20221.847ZM76.1236%20225.041C74.8354%20225.041%2073.6391%20224.778%2072.5349%20224.253C71.4307%20223.727%2070.5499%20223.017%2069.8926%20222.123C69.2616%20221.203%2068.9462%20220.191%2068.9462%20219.086C68.9462%20217.351%2069.656%20215.931%2071.0757%20214.827C72.5217%20213.697%2074.4673%20212.961%2076.9124%20212.619L82.7884%20211.791V210.647C82.7884%20207.965%2081.2504%20206.624%2078.1743%20206.624C77.0175%20206.624%2076.071%20206.874%2075.3349%20207.374C74.5987%20207.847%2074.0466%20208.412%2073.6785%20209.07C73.5997%20209.306%2073.4945%20209.477%2073.3631%20209.582C73.2579%20209.687%2073.1001%20209.74%2072.8898%20209.74H71.194C70.9574%20209.74%2070.7471%20209.661%2070.5631%20209.503C70.4053%20209.319%2070.3264%2020 [...]

2021-11-11 01:03 UTC, ajbozarth commented
> tried with a few pipelines I had from 3.2 but after migration box clicked ok, shows blank canvas.

That's because I haven't pushed any updates yet to handle all the recent changes, I should have those pushed by EOD

2021-11-19 21:46 UTC, akchinSTC commented
Address image icons in migration 
see related : https://github.com/elyra-ai/elyra/pull/2305

2021-11-21 05:59 UTC, lresende commented
Please validate by migrating covid and flight delays and make sure they run to completion.

NOT A CONTRIBUTION

2021-11-23 19:59 UTC, ajbozarth commented
I've pushed the final working migration code for review, I still need to add/update the tests but this should be good to review now.

I've opened https://github.com/elyra-ai/elyra/pull/2321 on the elyra side for testing. That PR points to the sandbox for this PR and includes the necessary code for triggering migration using elyra.

2021-11-23 22:00 UTC, ptitzler commented
Should try to tweak the wording to use fewer instances of "example components". Current message:

```
The pipeline you are trying to migrate uses example components.
Example components are no longer included in the base Elyra install.
Follow the "Example Custom Components Documentation" to learn how to install the example components before migrating this pipeline.
```

Proposal:

```
The pipeline you are trying to migrate uses example components, which are not 
enabled in your environment. Complete the setup instructions in "Example Custom Components" and try again.
```

2021-11-23 22:12 UTC, ptitzler commented
https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/email_operator doesn't seem to work as expected:

![image](https://user-images.githubusercontent.com/13068832/143137193-cc2da6bf-75cd-4c36-8738-050c325bfc10.png)

2021-11-23 22:32 UTC, ptitzler commented
https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/spark_sql_operator fails migration:

![image](https://user-images.githubusercontent.com/13068832/143139567-ed5e80e5-7f5f-4e33-8a48-1e0516d0c0d6.png)

2021-11-23 22:33 UTC, ptitzler commented
https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/spark_submit_operator fails migration:

![image](https://user-images.githubusercontent.com/13068832/143139723-9c394695-ba7e-49a1-b4b1-dd372f680aa5.png)

2021-11-23 22:35 UTC, ptitzler requested changes
See failing example pipelines

2021-11-24 17:12 UTC, ptitzler commented
Following up to today's dev meeting discussion https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/spark_sql_operator and https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/spark_submit_operator  were refreshed [by the same PR](https://github.com/elyra-ai/examples/commit/0c87f9976705c9525b785c048488fd2d696737a6). Only these  two pipelines define the `component_source` property as a child property of `component_parameters`, whereas all other pipelines define it as a sibling.

2021-11-24 18:01 UTC, ptitzler commented
https://github.com/elyra-ai/examples/pull/83 updates the two problematic pipelines, which should resolve the root cause for above failures.

2021-11-24 18:09 UTC, ptitzler commented
> [elyra-ai/examples#83](https://github.com/elyra-ai/examples/pull/83) updates the two problematic pipelines, which should resolve the root cause for above failures.


Confirmed that migration produces the expected results for the updated pipeline files

2021-11-29 18:53 UTC, ajbozarth commented
> https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/email_operator doesn't seem to work as expected after migration:

just pushed a fix for this, will be updating the code sandbox link on the elyra PR once I check the build locally

2021-11-29 20:22 UTC, ptitzler commented
> > https://github.com/elyra-ai/examples/tree/master/pipelines/airflow_component_examples/email_operator doesn't seem to work as expected after migration:
> 
> just pushed a fix for this, will be updating the code sandbox link on the elyra PR once I check the build locally

Confirmed that node properties are displayed as expected for email op

2021-11-29 23:48 UTC, ptitzler approved these changes
LGTM based on  https://github.com/elyra-ai/elyra/pull/2321#issuecomment-977219357

2021-11-30 00:05 UTC, kiersten-stokes approved these changes
LGTM! All example components are migrating perfectly, and I like the error messaging for when it can't find a component

2021-11-30 17:12 UTC, merged